apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clouds-app-dev
  namespace: openshift-gitops
spec:
  project: quarkus-getting-started
  source:
    repoURL: 'https://github.com/giofontana/quarkus-quickstarts.git'
    path: getting-started/k8s/overlays/dev
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
