apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: quarkus-getting-started
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: 'ArgoCD Project dedicated for quarkus-getting-started application'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
