apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: dev

namespace: quarkus-getting-started-dev

bases:
  - ../../base

resources:
  - namespace.yaml

images:
- name: change-me-image
  newName: quay-registry-quay-openshift-operators.apps.cluster-gf.gf.sandbox1212.opentlc.com/company/quarkus-getting-started
  newTag: latest