apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: dev

namespace: quarkus-getting-started-dev

bases:
  - ../../base

resources:
  - namespace.yaml

images:
- name: change-me-image
  newName: image-registry.openshift-image-registry.svc:5000/cicd/quarkus-getting-started
  newTag: v1.0